import type { Recipe } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id);

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'spaghetti-bolognese',
    title: 'Spaghetti Bolognaise',
    description: 'Un grand classique de la cuisine italienne, riche et réconfortant.',
    category: 'Plat Principal',
    prepTime: 20,
    cookTime: 120,
    servings: 4,
    ingredients: [
      { id: '1', name: 'Spaghetti', quantity: '400g' },
      { id: '2', name: 'Viande de bœuf hachée', quantity: '500g' },
      { id: '3', name: 'Oignons', quantity: '2' },
      { id: '4', name: 'Carottes', quantity: '2' },
      { id: '5', name: 'Branches de céleri', quantity: '2' },
      { id: '6', name: 'Tomates pelées en conserve', quantity: '800g' },
      { id: '7', name: 'Vin rouge', quantity: '150ml' },
      { id: '8', name: 'Parmesan râpé', quantity: 'pour servir' },
    ],
    steps: [
      'Hacher finement les oignons, les carottes et le céleri.',
      'Faire revenir les légumes dans une grande casserole avec de l\'huile d\'olive.',
      'Ajouter la viande hachée et faire dorer.',
      'Déglacer avec le vin rouge et laisser réduire.',
      'Ajouter les tomates pelées, écraser avec une cuillère, saler et poivrer.',
      'Laisser mijoter à feu doux pendant au moins 2 heures.',
      'Cuire les spaghetti selon les instructions du paquet.',
      'Servir la sauce sur les pâtes avec du parmesan râpé.',
    ],
    imageUrl: getImage('spaghetti-bolognese')?.imageUrl ?? '',
    imageHint: getImage('spaghetti-bolognese')?.imageHint ?? '',
  },
  {
    id: 'chocolate-fondant',
    title: 'Fondant au Chocolat',
    description: 'Un dessert irrésistible au cœur coulant pour les amateurs de chocolat.',
    category: 'Dessert',
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    ingredients: [
      { id: '9', name: 'Chocolat noir de qualité', quantity: '200g' },
      { id: '10', name: 'Beurre', quantity: '150g' },
      { id: '11', name: 'Œufs', quantity: '4' },
      { id: '12', name: 'Sucre en poudre', quantity: '100g' },
      { id: '13', name: 'Farine', quantity: '50g' },
    ],
    steps: [
      'Préchauffer le four à 200°C (thermostat 6-7).',
      'Faire fondre le chocolat et le beurre au bain-marie.',
      'Dans un saladier, fouetter les œufs et le sucre jusqu\'à ce que le mélange blanchisse.',
      'Incorporer le mélange chocolat-beurre fondu.',
      'Ajouter la farine et mélanger délicatement.',
      'Verser la pâte dans des ramequins beurrés et farinés.',
      'Enfourner pour 10 à 12 minutes. Le centre doit rester liquide.',
      'Servir immédiatement, éventuellement accompagné d\'une boule de glace vanille.',
    ],
    imageUrl: getImage('chocolate-fondant')?.imageUrl ?? '',
    imageHint: getImage('chocolate-fondant')?.imageHint ?? '',
  },
  {
    id: 'pumpkin-soup',
    title: 'Velouté de Potimarron',
    description: 'Une soupe douce et onctueuse, parfaite pour les soirées d\'automne.',
    category: 'Entrée',
    prepTime: 10,
    cookTime: 25,
    servings: 6,
    ingredients: [
      { id: '14', name: 'Potimarron', quantity: '1' },
      { id: '15', name: 'Oignon', quantity: '1' },
      { id: '16', name: 'Bouillon de légumes', quantity: '1L' },
      { id: '17', name: 'Crème fraîche', quantity: '20cl' },
      { id: '18', name: 'Noix de muscade', quantity: '1 pincée' },
    ],
    steps: [
      'Laver le potimarron, le couper en deux et retirer les graines. Le couper en morceaux (pas besoin de l\'éplucher).',
      'Émincer l\'oignon et le faire revenir dans une grande casserole avec un peu de beurre.',
      'Ajouter les morceaux de potimarron et couvrir avec le bouillon de légumes.',
      'Laisser cuire 20-25 minutes jusqu\'à ce que le potimarron soit tendre.',
      'Mixer la soupe jusqu\'à obtenir une consistance veloutée.',
      'Ajouter la crème fraîche et la noix de muscade. Saler, poivrer.',
      'Réchauffer doucement sans faire bouillir et servir chaud.',
    ],
    imageUrl: getImage('pumpkin-soup')?.imageUrl ?? '',
    imageHint: getImage('pumpkin-soup')?.imageHint ?? '',
  },
  {
    id: 'mojito',
    title: 'Mojito',
    description: 'Le cocktail cubain emblématique, frais et plein de saveurs.',
    category: 'Boisson',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    ingredients: [
      { id: '19', name: 'Rhum blanc', quantity: '5cl' },
      { id: '20', name: 'Feuilles de menthe fraîche', quantity: '10' },
      { id: '21', name: 'Sucre de canne', quantity: '2 cuillères à café' },
      { id: '22', name: 'Citron vert', quantity: '1/2' },
      { id: '23', name: 'Eau gazeuse', quantity: 'pour compléter' },
      { id: '24', name: 'Glace pilée', quantity: 'abondamment' },
    ],
    steps: [
      'Dans un verre, déposer les feuilles de menthe et le sucre.',
      'Couper le demi-citron vert en quartiers et les ajouter dans le verre.',
      'Piler délicatement pour extraire les sucs sans broyer les feuilles de menthe.',
      'Remplir le verre de glace pilée.',
      'Verser le rhum.',
      'Compléter avec de l\'eau gazeuse.',
      'Mélanger avec une cuillère, décorer d\'une tête de menthe et servir.',
    ],
    imageUrl: getImage('mojito')?.imageUrl ?? '',
    imageHint: getImage('mojito')?.imageHint ?? '',
  }
];
